/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface StBtn {
    'display': string;
    'onClickHandler': (btnName: string) => void;
  }
  interface StBtnGroup {
    'btns': string[];
    'display': string;
    'onClickHandler': (target: string) => void;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLStBtnElement extends Components.StBtn, HTMLStencilElement {}
  var HTMLStBtnElement: {
    prototype: HTMLStBtnElement;
    new (): HTMLStBtnElement;
  };

  interface HTMLStBtnGroupElement extends Components.StBtnGroup, HTMLStencilElement {}
  var HTMLStBtnGroupElement: {
    prototype: HTMLStBtnGroupElement;
    new (): HTMLStBtnGroupElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'st-btn': HTMLStBtnElement;
    'st-btn-group': HTMLStBtnGroupElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface StBtn extends JSXBase.HTMLAttributes<HTMLStBtnElement> {
    'display'?: string;
    'onClickHandler'?: (btnName: string) => void;
  }
  interface StBtnGroup extends JSXBase.HTMLAttributes<HTMLStBtnGroupElement> {
    'btns'?: string[];
    'display'?: string;
    'onClickHandler'?: (target: string) => void;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'st-btn': StBtn;
    'st-btn-group': StBtnGroup;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


